### ISSUE TITLE
Support Creating DOIs through EZID and DataCite

### ISSUE THREAD

**Issue by rickjohnson** [samvera-labs/doi_registrar#3]

**Comment by rickjohnson** [comment]
The group will look to use the same connector to both EZID and DataCite with the EZ API support see #2

**Comment by rickjohnson** [comment]
Use EZ API for datacite and EZID API for EZID, investigate using Duke's ezid client and mahonia implementation as baseline.
https://github.com/curationexperts/mahonia

**Comment by jamesvanmil** [comment]
I spent some time looking at the tools/code we have to work from, taking notes here: https://gist.github.com/jamesvanmil/529b165c735fbc5ab68d900b8584878a

I feel like the structure of Mahonia, which would be simplified by using something like EZID-client, provides a really straightforward back-end for DOI wrangling.

**Comment by rickjohnson** [comment]
Next step is to breakup this issue into smaller tasks. James will work on breaking these out mirroring the pattern in Mahonia.

**Comment by rickjohnson** [comment]
Likely architectural components...

Use ezid-client that already supports talking to both DataCite and EZID (satisfies 1 and 2 below)...

1. Configuration to point to doi service provider (DataCite or EZID) -> credentials, url, etc
2. EZ API implementation that defines all relevant requests
3. Default Hyrax UI views, controls using the connector that can be customized as needed with main operations like create, modify with required and optional fields

Next steps to look at #3 above

**Comment by rickjohnson** [comment]
#3 is done if considering for ezid-client
