### ISSUE TITLE
Define DOI Connector Interface and proper level of Abstraction

### ISSUE THREAD

**Issue by rickjohnson** [samvera-labs/doi_registrar#6]
As the DOI connector is meant to support connections with multiple DOI services need to:

-Assess common elements across each of EZID, DataCite, and CrossRef
   - common metadata elements like id, title, resource uri, etc.
   - common object models like metadata record, resource uri
   - common operations across each

Generalize connector API interface to support operations.  Some may or not be supported by each, and perhaps leave un-implemented if not

**Comment by rickjohnson** [comment]
@barmintor will reach out to valkyrie data mapper folks for any insights on approaching this

**Comment by jamesvanmil** [comment]
Initial look at APIs here: https://docs.google.com/document/d/1uXiQaUQTAZKQEpAGWhCPP1l7OQS0yG04FWsxSsfsuns/edit#
