### ISSUE TITLE
Support Creating DOIs through CrossRef

### ISSUE THREAD

**Issue by rickjohnson** [samvera-labs/doi_registrar#7]

**Comment by shlake** [comment]
UVa was getting CrossRef DOIs through EZID. But will no longer now that we are migrating to DataCite. It will have additional costs. Was free with EZID.

**Comment by rickjohnson** [comment]
Close this ticket?

**Comment by shlake** [comment]
Do we know who in Samvera Community wants to mint DOIs via CrossRef? Maybe put this lower down on the priority list (last?) and only move it if someone needs the functionality?

**Comment by rickjohnson** [comment]
Need to survey community on this.  From James Van Mil the interface and workflow is fairly different from EZID and Datacite, where it expects a batch of XML documents to be submitted somehow (unclear if there is a programmatic API available).  So, will likely look at this as a later step to incorporate depending on priority within the community.

Duke will be looking at this in the next 2-4 weeks.

**Comment by rickjohnson** [comment]
Closing this for now as no urgency to support CrossRef as well, but may want to reopen in the future.
